### ISSUE TITLE
Figuring out vorbis errors

### ISSUE THREAD

**Issue by Gfurst** [GreatEmerald/OggVorbisFix#1]
Hey there, my issue may not be specifically related with this repo, but seeking help is quite hard on the subject.

Recently I browsing/sorting through some of my fresh encoded vorbis files, only to find out a few of them were unplayable, this was odd as I was sure I had tested them well and even listened to them a couple of times before. At the time I found they were corrupt, at the time I found them, I had just moved from the converting bed to my library, all using Amarok media player, and as you can imagine its my prime suspect.

Right after that I've found even more files getting corrupt in my library, and sometimes even minutes after last listening to them, so you can imagine my despair. I'd even check for disk failure of something similar, but tests went ok and only ogg files targeted. 

Anyway, not sure where to look for help anymore, I've already tried tools like mp3splt, oggfix, and your own. Error seems to be on "corrupt secondary header"

**Comment by GreatEmerald** [comment]
Huh. Interesting. I made this tool exactly because of a problem like that... And I'm using Amarok too. Which version are you using? I'm currently using amarok5 (frameworks git), and that might be the reason why...
Also, is it the same for you that when you open the files in the hex editor, the first bytes are mostly zeroes with a 1 every now and then? If so, my tool should work for the most part. It might still be not playable with Amarok after using it, but it should be readable with FFmpeg. Though also not always, depends on how many bytes were overwritten.
Also, to make sure it doesn't happen again, just `chmod -w` all your ogg files. Except a few that you might want to test on, that is.

**Comment by Gfurst** [comment]
Hey thanks for the reply, so I had some more development on the issue: at the very least one bug matches it https://bugs.kde.org/show_bug.cgi?id=369672
So it seems to be happening with Amarok when changing tags, at least specifically for me when changing between various artists or not, I was able to replicate with at least another file.

I've also brought up the matter within the vorbis mail-list to see if someone can come up with a workaround. But anyway, I've also tried the ffmpeg copy track after using the tools, still ffmpeg doesn't recognize the format, I might try manually passing the codec to the input as well.
As for the hex editor, I've never really used one, so I might some hand holding on that, what utility can I use? (on Arch linux btw)

**Comment by GreatEmerald** [comment]
Did you actually edit the tags? In my case things get corrupted without editing anything (manually, at the very least). Hmm.

Yea, that sounds like the corruption is larger than just the header, then it won't work. Mind you, for me different files got corrupted with different length of the header getting erased, so the tool works on some files but not others. If FFmpeg refuses to recognise it, then no extra parameters will help, sorry.

The hex editor I use is Okteta, the KDE hex editor. It's pretty simple: open a bad file, then open a good file, and compare the top rows. The problem will be very easy to see right off the bat. This is how I made this tool, it simply copies the bytes from non-broken headers. The problem is that OGG files also have CRC checksums of the content, and that's not something that can be made to match if any of the content itself, not just the header, is corrupt...

If there is something else that can be done as per the mailing list, keep me informed and I'll see if I can put that functionality into this tool.

**Comment by Gfurst** [comment]
Damn, so if the damage is more than we can imagine then the file is lost.
I'll check the hex editor later. And the bug filed, we will try figure out if the issue comes from Amarok itself or some backend used to handle ogg files.

**Comment by GreatEmerald** [comment]
It's not lost per se, the data is all there, it's just the header that gets overwritten. It's just that beyond the first 48 bytes, the first vorbis stream starts, and I don't know the spec enough to make guesses as to what the bytes there mean and thus what they should be. It's nothing terribly important, as right after that the Vorbis tags are listed. The actual audio starts only at around 345 bytes into the file (more or less depending on how many tags you have and if there is an embedded album picture).

There is also a second CRC checksum there, which might also be problematic (not sure whether FFmpeg cares about those or not). And a strange variable-length field of 0xFFs, which I don't really know about either. I could test a few more things and see whether I can make it work beyond 48 bytes, though. Mind you, I didn't keep any of the corrupt files myself, so I don't have anything to test on, hm.

**Comment by Gfurst** [comment]
I'll wait to hear from the guy in the vorbis mail list, ask him to chime in too.
tried ffmpeg again with specified input options, it just exits with `filename: end of file`
If its matter of just the checksum and headers, then it could be possible to recalculate those like the encoder normally does (?).
Anyway, I could share one of my damaged files. https://drive.google.com/file/d/0BxmeqItErkUFRnJlWmRLUVJodFk/view?usp=drive_web

**Comment by GreatEmerald** [comment]
I'm reading the spec now, and yes, I think I can make my tool work with further corruption. Some metadata includes the number of channels and the bitrate, which I can't recreate, but I can make the tool ask you to input it, so that you can guess it. And yes, technnically FFmpeg should be able to recalculate the checksums after the file is made readable.
As for the files, I don't need the whole thing, but a screenshot of the first bytes in the hex editor would help (also to make sure that we got hit by the same bug).

**Comment by GreatEmerald** [comment]
OK, try now, I made it fix corruption up to the 71st byte. It should be enough.

Mind you, my code assumes 2 channel 44100 sample rate 256 kbps bitrate audio at the moment. If it's say 48000, the audio will sound slowed down until you recompile the tool with the appropriate SampleRate value (which would be `\x80\xbb\x00\x00` in the case of 48000) and rerun it. I might make a dialog for choosing something else in the future.

**Comment by GreatEmerald** [comment]
Oh, now I noticed your file. That's very weird. Do you have a version that has corruption that has not been changed with fixing tools? Because from the looks of it, that file is perfectly fine save for the frame length information being missing for some weird reason. And also audio data not starting with a "vorbis" string. That is super weird and looks nothing like what I'm seeing in my files.

**Comment by Gfurst** [comment]
Hey sorry I kinda missed your last messages and then forgot. Here is another file which I'm mostly sure didn't try to fix.
https://drive.google.com/file/d/0BxmeqItErkUFdnVmY1pXU05aWEE/view?usp=sharing

And possibly some more information, apparently all of these files look fine looking from mediainfo, including frequency, bitrate and etc.

**Comment by GreatEmerald** [comment]
Yea, indeed, so your corruption is something completely different, it's OggS packets that are inserted in the middle of the cover image for no apparent reason, while other things like vorbis packet headers (and probably good chunks of the data around them) are missing.
So unfortunately this tool can't help you, and I doubt anything can fix that sort of corruption altogether. It's not just the headers that are overwritten, it's the data itself that's been displaced and parts of it are missing altogether.

**Comment by Gfurst** [comment]
Gosh, well thanks, it was worth the try. Damn gonna stay away from Amarok for a while.
I see you're already following on bug tracker, lets hope we can find at least whats the source of this.
